<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RPIPL-NB-DL018" ignored="0" name="RetryMulitpleFailedTestCases" tests="6" failures="1" timestamp="2021-08-23T13:15:09 IST" time="0.218" errors="0">
  <testcase name="Test1" time="0.018" classname="testNG.RerunTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="testNG.RerunTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.006" classname="testNG.RerunTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="testNG.RerunTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG.RerunTest.Test1(RerunTest.java:12)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="testNG.RerunTest"/>
  <testcase name="Test3" time="0.001" classname="testNG.RerunTest"/>
</testsuite> <!-- RetryMulitpleFailedTestCases -->
